In [1]:
import numpy as np
from classes.reward import Reward
from classes.constraints import Constraints
from classes.problem import Problem
from reward_functions import *
from dynamic import *
from scipy.stats import norm
from config import initialize_config
from utils.matrix_verif import *
# from sklearn.linear_model import LassoLars
# from sklearn.linear_model import Lars
from scipy.optimize import linprog
# from sklearn.preprocessing import StandardScaler
# import pandas as pd
# from sklearn.linear_model import lasso_path



In [2]:
config = initialize_config()

Time = config["Time"]
Delta = config["Delta"]
State = config["State"]
delta = config["delta"]
State_mesh_m = config["State_mesh_m"]
Time_mesh_m = config["Time_mesh_m"]
Time_mesh_lam = config["Time_mesh_lam"]
State_mesh_lam = config["State_mesh_lam"]
combined_state0 = config["combined_state0"]
combined_state1 = config["combined_state1"]
m0 = config["m0"]
U = config["U"]
d_t = config["d_t"]
d_s = config["d_s"]
d_j = config["d_j"]
tol = config["tol"]
N_iter = config["N_iter"]
m_tilde_0 = config["m_tilde_0"]
lam_tilde_0 = config["lam_tilde_0"]
print('delta',delta)
print('Delta',Delta)
def initialize_reward_and_constraints():
    """
    Initialize the Reward and Constraints objects.
    """
    # Define the reward functions
    f1 = f1_factory(m_tilde_0,State,Time)
    f2 = f2_factory(lam_tilde_0,State,Time)
    g = g_factory(m_tilde_0,State)

    # Create a Reward object
    reward = Reward(State_mesh_m, Time_mesh_m, State_mesh_lam, Time_mesh_lam, State, Delta, delta, f1, f2, g)

    # Define the drift term
    b=b_factory(Time,State)
    # Define the diffusion term
    sigma=s_factory(Time,State)
    # Create a Constraints object
    constraints = Constraints(State_mesh_m, Time_mesh_m,State_mesh_lam, Time_mesh_lam,State,Time ,Delta, delta,U , m0, b, sigma)

    return reward, constraints


# print(U)
# print(State[-3,0])
# print(State)


delta 1.0
Delta 0.1


In [3]:
print(delta**2/(1+delta)-Delta)

0.4


In [4]:
def main():
    # Initialize the Reward and Constraints objects
    reward, constraints = initialize_reward_and_constraints()

    # Create a Problem object
    problem = Problem(State_mesh_m,Time_mesh_m,State_mesh_lam,Time_mesh_lam,m_tilde_0, lam_tilde_0,State,Time ,Delta, delta, constraints, reward,tol,N_iter,f1_factory,f2_factory,g_factory)

    # Compute the optimal solution
    value, lam_bar, m_bar, lam_hat, m_hat, eps_array = problem.compute_optimal_solution()

    return value, lam_bar, m_bar, lam_hat, m_hat, eps_array




In [9]:
value, lam_bar, m_bar, lam_hat, m_hat, eps_array = main()
print(lam_bar)

Set parameter LogToConsole to value 0
Set parameter LogToConsole to value 0
Iteration:    1; Error:  0.000000
[[[ 0.00000000e+00  6.69153123e-05]
  [ 2.21593081e-03  2.69955637e-02]
  [ 1.20985723e-01  1.99471735e-01]
  [ 1.20985723e-01  2.69955637e-02]
  [ 2.21593081e-03  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00]]

 [[ 0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00]
  [ 6.69153123e-06  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00]]

 [[ 0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00 -1.

In [6]:
# # Define the drift term
# b=b_factory(Time,State)
# # Define the diffusion term
# sigma=s_factory(Time,State)
# constraints = Constraints(State_mesh_m, Time_mesh_m,State_mesh_lam, Time_mesh_lam,State,Time ,Delta, delta,U , m0, b, sigma)

# A_eq = constraints.A_eq
# b_eq = constraints.b_eq
# # for i in range(A_eq.shape[0]):
# #     print('counter:',i)
# #     print(A_eq[i,:].todense().reshape(d_t,(d_s-2)*d_j))
# #     print(b_eq[i])
# # print(b_eq)

In [7]:
# for i in range(A_eq.shape[0]):
#     print('counter:',i)
#     print(constraints.A_eq_mterm[i,:].todense())

In [8]:

# print(np.linalg.matrix_rank(A_eq.todense()))
# print(np.linalg.matrix_rank(np.concatenate((A_eq.todense(),b_eq.reshape(-1,1)),axis=1)))
# c=np.zeros(A_eq.shape[1])
# res=linprog(c, A_eq = A_eq, b_eq = b_eq, method ='highs',options={'disp': True},bounds=(0, None))
# print(res)
# print(res.x)
# for i in range(d_t):
#     print(np.sum(res.x[i*(d_s-2)*d_j:(i+1)*(d_s-2)*d_j]))
#     print((i+1)*(d_s-2)*d_j)
# print(res.x.shape)